import PreferencesUtils from './src/main/ets/components/mainpage/PreferencesUtils'
export { MainPage } from './src/main/ets/components/mainpage/MainPage'
export { HttpManager } from './src/main/ets/components/mainpage/HttpManager'
export { AbsHttpRequest } from './src/main/ets/components/mainpage/AbsHttpRequest'
export { GetMethod ,Param,PostMethod,PostJsonMethod,FunctionParam,GetUrlValueMethod} from './src/main/ets/components/mainpage/decorator/DecoratorFunction'

export default PreferencesUtils
