import { ArticleItem } from '../entity/ArticleItem'
export const  ARTICLELIST: ArticleItem[] = [
  new ArticleItem(1, "嫦娥六号探测器进入环月轨道飞行", "https://p5.img.cctvpic.com/photoworkspace/contentimg/2024/05/08/2024050820144382684.jpg", "央视网", "2014-05-08"),
  new ArticleItem(2, "“五一”假期游处处火爆 有哪些文旅新潮流？", "https://cms-emer-res.cctvnews.cctv.com/image/1005/upload/17292d188bc64cef882f1cd07d3d2acc.jpeg", "央视新闻客户端", "2024-05-08"),
  new ArticleItem(3, "杭州：全面取消住房限购，购房即可申请落户", "https://up.enterdesk.com/edpic/be/fb/bd/befbbdb0df6364d047eb1b572c59fe5f.jpg", "界面新闻", "2024-05-09"),
  new ArticleItem(4, "时隔五年，合肥或将再次引进“国宝”大熊猫", "https://pics4.baidu.com/feed/d50735fae6cd7b899b1d7bef7ec7b8aad8330e5d.jpeg@f_auto?token=e70fa976dceb8e88433c493f7e86b88c", "九派新闻", "2024-05-08"),
  new ArticleItem(5, "发布擦边广告再被罚，椰树集团徘徊在“土味”和“低俗”之间？", "https://pics1.baidu.com/feed/e824b899a9014c083cd8d85d067bf9057af4f471.jpeg@f_auto?token=c6770b5d0d99a68721fc88e7a337d01c", "北京商报", "2024-05-08"),
  new ArticleItem(6, "特斯拉在华推进全自动驾驶 智能网联车产业链迎新机遇", "https://up.enterdesk.com/edpic/be/fb/bd/befbbdb0df6364d047eb1b572c59fe5f.jpg", "每日经济新闻", "2024-05-09"),
  new ArticleItem(7, "嫦娥六号探测器进入环月轨道飞行", "https://p5.img.cctvpic.com/photoworkspace/contentimg/2024/05/08/2024050820144382684.jpg", "央视网", "2014-05-08"),
  new ArticleItem(8, "“五一”假期游处处火爆 有哪些文旅新潮流？", "https://cms-emer-res.cctvnews.cctv.com/image/1005/upload/17292d188bc64cef882f1cd07d3d2acc.jpeg", "央视新闻客户端", "2024-05-08"),
  new ArticleItem(9, "杭州：全面取消住房限购，购房即可申请落户","https://up.enterdesk.com/edpic/be/fb/bd/befbbdb0df6364d047eb1b572c59fe5f.jpg", "界面新闻", "2024-05-09"),
  new ArticleItem(10, "时隔五年，合肥或将再次引进“国宝”大熊猫", "https://pics4.baidu.com/feed/d50735fae6cd7b899b1d7bef7ec7b8aad8330e5d.jpeg@f_auto?token=e70fa976dceb8e88433c493f7e86b88c", "九派新闻", "2024-05-08"),
  new ArticleItem(11, "发布擦边广告再被罚，椰树集团徘徊在“土味”和“低俗”之间？", "https://pics1.baidu.com/feed/e824b899a9014c083cd8d85d067bf9057af4f471.jpeg@f_auto?token=c6770b5d0d99a68721fc88e7a337d01c", "北京商报", "2024-05-08"),
  new ArticleItem(12, "特斯拉在华推进全自动驾驶 智能网联车产业链迎新机遇", "https://up.enterdesk.com/edpic/be/fb/bd/befbbdb0df6364d047eb1b572c59fe5f.jpg", "每日经济新闻", "2024-05-09"),
]

export const BANNER_IMAGE_URL =  [
  "https://file.moyublog.com/d/file/2021-05-19/30855f1b0577e65e0a0f3bd6fb20f3d7.jpg",
  "https://i1.hdslb.com/bfs/archive/7bfa09bfbec879b1b59b0d0d957a1442d12e94f5.jpg",
  "https://tva1.sinaimg.cn/large/0032l8l0gy1gsimek11vgj61z4140x6p02.jpg"
]